logging:
  level:
    org.springframework.web: ERROR
    com.microservices.controllers: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:\Users\m.estrada.hernandez\Documents\workspace-sts\microservices\application.log